name: GlintSolar
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.4
  - mamba=0.19.0
  - pip=21.3.1
  - python=3.9.7
  - setuptools=59.4.0
  - wheel=0.37.0
  - dvc=2.8.3
  - geopandas=0.10.2
  - matplotlib=3.5.0
  - pygeos=0.11.1
  - rasterio=1.2.10
  - cartopy=0.20.1
  - sentinelsat=1.1.0
  - earthpy=0.9.4
  - seaborn=0.11.2
  - rioxarray=0.9.0
  - datacube=1.8.6
  - geopy=2.2.0
  - nc-time-axis=1.4.0
  - pip:
    - pystac-client=0.3.1
    - stackstac[viz]=0.2.2
